### ISSUE TITLE
Desenvolvimento dos Cards (Serviços)

### ISSUE THREAD

**Issue by LoriaLawrenceZ** [OZimbres/FIAP-Cap5-Grupo2#9]
# CARDS | Serviço

## Desenvolvimento

Necessário realizar o desenvolvimento da lista de cards de serviço de acordo com a documentação oferecida na tarefa.

Informações relevantes:

![Informações Card Serviços](https://github.com/OZimbres/FIAP-ATV1-G2/assets/97912499/c5281446-1c61-4388-973a-06b34c0aea05 "Informações Card Srerviços")

Resultado esperado:

![Resultado Esperado](https://github.com/OZimbres/FIAP-ATV1-G2/assets/97912499/7f099ff4-0725-4193-9e00-43d2ef629412 "Resultado Esperado")

## ✅ Task List

- [ ] Estrutura Base
    - [ ] Cabeçalho (Serviços + ícone de drone)
    - [ ] Card "Cursos"
    - [ ] Card "Manutenções"
    - [ ] Card "Filmagens Aéreas"
- [ ] Estilização
    - [ ] Fonte Correta
    - [ ] Cores de acordo com o exemplo
